group_imports = "StdExternalCrate"
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"

reorder_impl_items = true
wrap_comments = true

fn_single_line = false
struct_lit_single_line = true

use_field_init_shorthand = true
use_try_shorthand = true

normalize_comments = true
normalize_doc_attributes = true

format_code_in_doc_comments = true
format_strings = true

overflow_delimited_expr = true
condense_wildcard_suffixes = true

hex_literal_case = "Upper"
